# Generated by Django 4.2.6 on 2023-11-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название урока')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('preview', models.ImageField(upload_to='preview/', verbose_name='превью урока')),
                ('url', models.URLField(verbose_name='ссылка на урок')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(upload_to='preview/', verbose_name='превью курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название курса'),
        ),
    ]
