# Generated by Django 4.2.6 on 2023-11-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0002_lessons_alter_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True, verbose_name='пользователь')),
                ('date_pay', models.DateField(blank=True, null=True, verbose_name='дата оплаты')),
                ('amount', models.IntegerField(verbose_name='сумма оплаты')),
                ('payment_choices', models.CharField(choices=[('наличные', 'day'), ('перевод', 'week')], default='наличные', max_length=15)),
                ('curs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curs.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curs.lessons')),
            ],
        ),
    ]
