# Generated by Django 4.2.6 on 2023-11-04 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curs', '0003_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curs.course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='превью курса'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='превью урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на урок'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
